# fly.toml app configuration file generated for bts-blog on 2024-01-01T00:00:00+00:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bts-blog-flask" # CHANGE THIS TO YOUR APP NAME
primary_region = "iad" # CST

[build]

[env]
  DATABASE_URL = "postgresql://user:password@postgres.internal:5432/bts_blog"

[deploy]
  release_command = "/bin/sh -c 'flask db upgrade && python seed_categories.py'"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"

[[services]]
  protocol = "tcp"
  internal_port = 5432
